### ISSUE TITLE
How do I override a method?

### ISSUE THREAD

**Issue by ErikGrimes** [polymer-dart/polymerize#5]
I've tried: 

```
namespace: Polymer
package-name:  polymer_elements
externals:
 "Polymer.IronFormElementBehavior": "package:polymer_elements/iron_form_element_behavior.dart"
 "Polymer.Templatizer": "package:polymer_element/polymer_element.dart"
 "Templatizer": "package:polymer_element/polymer_element.dart"
components:
 - name :    "iron-validator-behavior"
   ref : "PolymerElements/iron-validator-behavior#2.0-preview"
   overrides:
     IronValidatorBehavior:
       validate: "bool validate(dynamic values);"
resolutions:
  "polymer": "2.0.0-rc.1"
```

**Comment by dam0vm3nt** [comment]
This will work : 
```
namespace: Polymer
package-name:  polymer_elements
externals:
 "Polymer.IronFormElementBehavior": "package:polymer_elements/iron_form_element_behavior.dart"
 "Polymer.Templatizer": "package:polymer_element/polymer_element.dart"
 "Templatizer": "package:polymer_element/polymer_element.dart"
components:
 - name :    "iron-validator-behavior"
   ref : "PolymerElements/iron-validator-behavior#2.0-preview"
   overrides:
     Polymer.IronValidatorBehavior:
       validate: 
         - "  extern bool validate(dynamic values);"
resolutions:
  "polymer": "2.0.0-rc.1"
```

Please note that you have to use `extern` keyword. And this will work only if you don't change the method name. To enable more generic mapping we should wait for `extensions method`  feature to be added to dart (https://github.com/dart-lang/sdk/issues/24779) please vote it!

**Comment by dam0vm3nt** [comment]
BTW : at the moment there is a `polymer` issue that make it impossible to use native old style (v.1) behavior with 2.0 component. see [here](https://github.com/Polymer/polymer/issues/4378) for info

**Comment by ErikGrimes** [comment]
What sort of problems does that cause for polymer-dart users? I read the
associated issues, but I'm not sure I understand the implications.

**Comment by dam0vm3nt** [comment]
Actually it turns out to be a `polymer-redux` problem. When mixin a behavior only the properties of the latest behavior that was mixed will be used by redux.

If you don't use redux there should be no problems then, but I hope `polymer-redux` people will fix it.

**Comment by dam0vm3nt** [comment]
type : `extern` -> `external`
