### ISSUE TITLE
Automatically rewrite index.html entrypoint

### ISSUE THREAD

**Issue by ErikGrimes** [polymer-dart/polymerize#7]
Currently, you have to know what what bazel is generating in order to setup the entrypoint.  IT would be nice if polymerize would transform your main entrypoint import automatically. So that

```
    <link rel='import' href="todo_main/todo_main.html" rel="import">
```

becomes

```
    <link rel='import' href="todo_main/todo_main.mod.html" rel="import">
```

**Comment by dam0vm3nt** [comment]
`IronMeta` is an strange element because it also defines the JS class `Polymer.IronMeta`. So there was a name clash. Had to map `<iron-meta>` with another JS class : `Polymer.IronMetaElement`.

**Comment by ErikGrimes** [comment]
Did you mean to close this?

**Comment by dam0vm3nt** [comment]
Ops, wrong ref on commit. Sorry

**Comment by dam0vm3nt** [comment]
polymerize now uses `pub+ddc`. then entry point follows the dart standard guidelines (`application/dart` script tag).
