### ISSUE TITLE
Wrong element name in package.mod.html

### ISSUE THREAD

**Issue by andrey-zakharov** [polymer-dart/polymerize#8]
I have created sample project with following simple structure:
```
lib/
lib/components/
lib/components/my_tag.html
lib/components/my_tag.dart
web/index.html
BUILD
pubspec.yaml
```
and other supplementary stuff.

Issue, that polymerize (bazel maybe) generated package.js with
```
  return {
    components__my_tag: components__my_tag,
    main: main
  };
```

while in package.mod.html its referenced as:
```
  polymerize.register(pkg.my_tag.MyTag,'my-tag',{
```

while inspecting pkg in debug, I could see `pkg.components__my_tag` member. So I've assume that 
package.mod.html has wrong component name in it.

**Comment by dam0vm3nt** [comment]
new release should solve that (no more `.mod.html` files though).
